### ISSUE TITLE
Sensor data looks like its being filtered on free run mode

### ISSUE THREAD

**Issue by cmydlarz** [floodnet-nyc/flood-sensor#33]
After running the Maxbotix vs teh Adafruir US sensors on the roof for >24hours, I see that the Maxbotix looks like it is filtering the distance data and jumps between discrete 10mm values as we saw when the filtered mode was switched on.

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/5649897/158072002-931b761c-7dcc-4e7a-8308-3e7e503a79f2.png">

This code was pulled from the main branch so I think is current.

Can we confirm what is going on?

**Comment by Praneethsvch** [comment]
The mode we currently use is `Triggered - Real-time Range Data`, in which we pull the `Pin 4` High for 20us before each sensor reading.

From the datasheet, 
- "When pin 4 is low and then brought high, the sensor will operate in real-time and the first reading output will be the range measured from this first commanded range reading. When the sensor tracks that the RX pin is low after each range reading, and then the RX pin is brought high, unfiltered real-time range information can be obtained."
- "Users can enter and remain in the real-time or triggered operation by making sure that before the end each range cycle, the voltage level on pin 4 is set low. After the sensor has completed the last reading, then Pin 4 is brought high. When Pin 4 is brought high, a brand new range cycle starts and the HRXL-MaxSonar-WR will output the most recent range data without filtering."


The same is implemented in the [sensor_singleread(void)](https://github.com/floodnet-nyc/flood-sensor/blob/cae1f3b738a08ccdb2f821b316072dfa37bfb746/firmware/src/maxbotix.cpp#L38) function. 


In contrast, `Free-Run Operation` uses a filter for increased accuracy and this needs the `Pin 4` to be on all times. 

From the datasheet, 
- "On the HRXL-MaxSonar-WR sensors, when pin 4 is left high, the sensor will continue to range, the data output includes a filter for increased accuracy in environments with acoustic noise."

**Comment by Praneethsvch** [comment]
Prior to using the serial output, Pulse-width output has an inaccuracy of 0.5% of serial output plus a different 1uS/mm resolution compared to serial, which is simply 1mm. In the latter, the microcontroller calculates the `distance` based on the duration or width of the incoming pulse which could further add inaccuracies from the clock.

**Comment by Praneethsvch** [comment]
This is the change of sensor reads from the beginning, just leaving here for reference:
1. old v2 sensors - Always ON, Trigger every 20us and digitalRead(PulseIn Output)

_Hoyt and 5th sensor data:_
<img width="986" alt="Screen Shot 2022-03-16 at 4 49 32 PM" src="https://user-images.githubusercontent.com/58634765/158688438-b8cb5c87-808f-4f33-88fc-24d9c5acd873.png">

2. April 5 2021     - Always ON, Trigger every 20us and Serial Read

_Carroll and 4th using feather:_
<img width="972" alt="Screen Shot 2022-03-16 at 4 48 35 PM" src="https://user-images.githubusercontent.com/58634765/158688286-d8127e1b-f740-4cae-88ee-5fa310cd397b.png">

_Carroll and 4th using Heltec:_
3. Nov 15, 2021    - Low-Power using Vext, Trigger every 20us, and Serial Read
<img width="987" alt="Screen Shot 2022-03-16 at 4 50 24 PM" src="https://user-images.githubusercontent.com/58634765/158688582-dddab7e2-f317-4566-ba4c-296c4fb821b8.png">

From the above series of events, this has been the case since the sensors completely shutdown every sleep cycle using Vext pin. 

_Further comments:_ You are right and I still can't comprehend this bug as it is counterintuitive. As the sensor is completely shut off from power, isn't it expected to reset and boot every time giving non-filtered readings? I speculate whether there is an internal memory that keeps track of filtering parameters that are saved beyond power cycles. However, this theory wouldn't hold as we are not running this on filtered-mode, unless something changed in their design since we started using them

**Comment by Praneethsvch** [comment]
Confirming that the **_Serial read using Trigger mode_** from the latest branch is giving filtered output. The resolution drops from `1 mm` to `1 cm` and the readings end with `2`.

Observations after testing:
- Picked a random sensor and with every combination of VEXT and  **_Serial read using Trigger mode_**, the output is same `1 cm` resolution with `2` at the end.
- The same sensor when rewired and operated without Serial pin, using Pulse width mode, the resolution is back to `1 mm` (the first deployments are with this configuration).

**Comment by Praneethsvch** [comment]
while loop at: https://github.com/floodnet-nyc/flood-sensor/blob/020fa2d212e8227fcd903d61b33d0e0d5af1e035/firmware/src/maxbotix.cpp#L49 was only reading in 3 characters. As this logic has been overlooked, now that it is solved by changing it to 4, the drop in resolution is ruled out

**Comment by Praneethsvch** [comment]
fixed a1d7071789cf7c05d9f0e98657d7d2f1241fa464
