### ISSUE TITLE
RCA - Q: Kissena Blvd/ Rose Ave

### ISSUE THREAD

**Issue by ak6492** [floodnet-nyc/flood-sensor#90]
Sensor Deployed:
November 16, 2023 by FloodNet

Sensor Version: v3.1. (cell)

Firmware Version:

Sensor Down:

deployment_id: doubtfully_popular_fawn

Sensor never charged since it had been deployed. Went down on November 25, 2023

**Comment by ak6492** [comment]
12/12: In lab RCA that the solar IC had not been soldered properly. The solar IC was incapable of charging. Replaced sensor with new one.

**Comment by ak6492** [comment]
follow up and check if sensor is charging correctly since replacement in a week

**Comment by Praneethsvch** [comment]
### Issue
- Sensor failed due to water ingress
- When water creeps in the sensor still operated but in bad conditions 
    - noisy data like battery data below from water damaged sensor 
    - It starts trending down or doesn't charge as well as the other sensors 
  
<img width="1088" alt="Screenshot 2024-01-16 at 4 25 38 PM" src="https://github.com/floodnet-nyc/flood-sensor/assets/58634765/7233455d-58eb-48f5-82d4-0f84abf85bd9">

  ### Metadata
  1. `doubtfully_popular_fawn `
  2. `fsc-00008` is damaged and now replaced with `fsc-00015`

  ### Fixes/Action
  - swapped with a new sensor 
  - To swap the plug with the n-type antenna ASAP

**Comment by ak6492** [comment]
02/12: Down completely since plug was swapped out with n-type antenna on 01/24. Did struggle to connect via nodered on the ground

**Comment by ak6492** [comment]
02/28: the switch was turned off physically. no other visible damage. up and running as of 03/05
